source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# default gems
gem 'rubocop-thread_safety'
gem "rubocop-performance"
gem 'rubocop-rails'
gem "rubocop-sorbet"
gem "rubocop-graphql"
gem "rubocop-minitest"
gem "rubocop-rake"
gem "rubocop-rspec"
gem "rubocop-i18n"
gem "rubocop-faker"
gem "rubocop-factory_bot"
gem "rubocop-md"
gem "rubocop-mdsol"
gem "rubocop-rspec_rails"
gem "rubocop-capybara"

# rubocop modules
gem "rubocop-gitlab-security"
gem "rubocop-haml"
gem "rubocop-anycable-rails"
gem "rubocop-require_tools"
gem "rubocop-shopify"
gem "rubocop-packaging"
gem "rubocop-rubycw"
gem "rubocop-packs"
gem "rubocop-changes"
gem "rubocop-migrations"
gem "rubocop-ast"

# Used by customer's config file or as dependencies
gem "yard"
gem "rake"
gem "graphql"
gem "sorbet-runtime"
gem "standard-rails"
gem "rollbar"
gem "sprockets-rails"
gem "sqlite3"
gem "stimulus-rails"
gem "sanitize_email"
gem "selenium-webdriver"
gem "simplecov"
gem "simplecov-cobertura"
gem "web-console"
gem "rubocop"
gem "turbo-rails"
gem "prettier"
gem "rdoc"
gem "rails"
gem "activesupport"
gem "actiontext"
gem "actionmailbox"
gem "actioncable"
gem "actionmailer"
gem "bigdecimal"
gem "bootsnap"
gem "capybara"
gem "importmap-rails"
gem "jbuilder"
gem "mocha"
gem "parser"
gem "pry"
gem "puma"
gem "safe_yaml"
gem "dark_finger"
