source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "yard"
gem "rake"
gem "rdoc"
gem "rails"
gem "activesupport"
gem "actiontext"
gem "actionmailbox"
gem "actioncable"
gem "actionmailer"
gem "bigdecimal"
gem "bootsnap"
gem "capybara"
gem "importmap-rails"
gem "jbuilder"
gem "mocha"
gem "parser"
gem "pry"
gem "puma"
gem "safe_yaml"
gem "dark_finger"
gem "rubocop-migrations"
gem "rubocop-minitest"
gem "rubocop"
gem "turbo-rails"
#Needed to be referenced on some user configs
gem "graphql"
gem "prettier"
#Rubocop official modules
gem "rubocop-capybara"
gem "rubocop-changes"
gem "rubocop-faker"
gem "rubocop-factory_bot"
gem "rubocop-i18n"
gem "rubocop-md"
gem "rubocop-mdsol"
gem "rubocop-performance"
gem 'rubocop-rails', require: false
gem "rubocop-rake"
gem "rubocop-rspec"
gem "rubocop-rspec_rails"
gem "rubocop-sorbet"
gem "rubocop-shopify", require: false
gem "rubocop-graphql"
gem 'rubocop-thread_safety', require: false
gem "rollbar"
gem "sprockets-rails"
gem "sqlite3"
gem "stimulus-rails"
gem "sanitize_email"
gem "selenium-webdriver"
gem "simplecov"
gem "simplecov-cobertura"
gem "standard"
gem "web-console"
